"""
Add metrics and metric_types table

Revision ID: af1be8b74d9f
Revises:     c3dad71f8e6b
Create Date: 2025-08-11 12:48:28.413380
"""

from logging import getLogger

from alembic import op
import sqlalchemy as sa



# Revision identifiers, used by Alembic.
revision = 'af1be8b74d9f'
down_revision = 'c3dad71f8e6b'
branch_labels = None
depends_on = None


def upgrade():
    LOG = getLogger("migration/report")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('metric_types',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('metric_type_name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('aggregate_method', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metric_types'))
    )
    op.create_table('metrics',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('run_history_id', sa.Integer(), nullable=False),
    sa.Column('metric_type_id', sa.Integer(), nullable=False),
    sa.Column('metric_value', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['metric_type_id'], ['metric_types.id'], name=op.f('fk_metrics_metric_type_id_metric_types')),
    sa.ForeignKeyConstraint(['run_history_id'], ['run_histories.id'], name=op.f('fk_metrics_run_history_id_run_histories')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_metrics'))
    )
    # ### end Alembic commands ###


def downgrade():
    LOG = getLogger("migration/report")
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('metrics')
    op.drop_table('metric_types')
    # ### end Alembic commands ###
